import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Layout/Header";
import { Content } from "@/components/Layout/Content";
import { Footer } from "@/components/Layout/Footer";
import { Container } from "@/components/shared/Container";

const robotoCOndensed = Roboto_Condensed({
  variable: "--roboto-condensed",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoCOndensed.variable} antialiased`}>
        <Header />
        <Content>
          <Container>{children}</Container>
          <Footer />
        </Content>
      </body>
    </html>
  );
}
